<?php

return [
    [
        "categories" => [2],
        "name" => "Haruka Sushi",
        "user_id"       => "1",
        "description" => "Esperienza culinaria incantata: Il nostro ristorante trasforma ingredienti ordinari in opere d'arte gustative, incantando i palati con un connubio magico di sapori e presentazioni uniche.",
        "city" => "Milano",
        "address" => "Corso San Gottardo, 49",
        "vat" => "2389176594",
        "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/00e175e9-bb69-4e6b-9545-8bab6f588e41/3145b280-208e-4de7-8e8c-34b0f38b3cf2.jpg",
        "priceRange" => 35,
        "rating_value" => 9,
        "review_count" => 150,
    ],
    [
        "categories" => [1, 4],
        "name" => "Slice",
        "user_id"       => "2",
        "description" => "Gusto del Futuro: Benvenuti nel ristorante dove la cucina innovativa abbraccia la tradizione, creando un viaggio gastronomico senza confini.",
        "city" => "Milano",
        "address" => "Via Giovanni Gherardini, 2",
        "vat" => "5098237461",
        "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/df09428f-0eed-402d-a815-2876597ea751/5965e5e3-f103-4068-8b8f-94e1d9193093.jpg",
        "priceRange" => 25,
        "rating_value" => 8,
        "review_count" => 267,
    ],
    [
        "categories" => [1, 4],
        "name" => "Il Fiore all'Occhiello",
        "user_id"       => "3",
        "description" => "Sapore Avventuroso, Destinazione Gustosa: Esplora i confini culinari mentre il nostro ristorante ti guida attraverso un mondo di sapori inaspettati e delizie straordinarie.",
        "city" => "Roma",
        "address" => "Via Costantino, 24",
        "vat" => "7168943025",
        "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/9eb1ab33-fe50-4da6-ac53-b40dd789c055/dd153129-ce8c-413c-b8e3-c9ff0e71f364.jpg",
        "priceRange" => 28,
        "rating_value" => 9,
        "review_count" => 7337,
    ],
    [
        "categories" => [1, 3],
        "name" => "Quarantuno Restaurant",
        "user_id"       => "4",
        "description" => "Ristorante Etereo: Dove i desideri gastronomici prendono vita, con piatti che sembrano provenire da un mondo incantato e profumi che raccontano storie dimenticate.",
        "city" => "Roma",
        "address" => "Via Ostiense, 39-41",
        "vat" => "6250193847",
        "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/963cb6e1-ec19-4d20-afd1-b13e553f9cfb/2685ccdd-d575-4713-b278-c35881cc6f94.jpg",
        "priceRange" => 25,
        "rating_value" => 8,
        "review_count" => 592,
    ],
//     [
//         "categories" => [1, 3, 4],
//         "name" => "San Paolino",
//         "description" => "Gastronomia in 4D: Nel nostro ristorante, i piatti non sono solo da gustare ma da vivere, con un'esperienza multisensoriale che sorprende e incanta.",
//         "city" => "Firenze",
//         "address" => "Via Palazzuolo, 9A",
//         "vat" => "4382759016",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/5b36ee28-ca6f-4ae8-8d17-65cfe3f117c8/c6ffc5f2-11af-4b6b-b288-26d05a1f686f.jpg",
//         "priceRange" => 35,
//         "rating_value" => 9,
//         "review_count" => 352,
//     ],
//     [
//         "categories" => [1, 4],
//         "name" => "Oliandolo Caffè Ristoro",
//         "description" => "Racconti di Sapori: Ogni piatto nel nostro locale racconta una storia unica, intrecciando ingredienti e creatività in un'esperienza culinaria da ricordare.",
//         "city" => "Firenze",
//         "address" => "Via Ricasoli, 38/40 R",
//         "vat" => "9016325847",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/60ab3bcf-ccaa-4dbb-99b5-b96ab62282b2/2a82617a-892b-47eb-95d4-120a6a92457c.jpg",
//         "priceRange" => 32,
//         "rating_value" => 4,
//         "review_count" => 193,
//     ],
//     [
//         "categories" => [1, 3, 4],
//         "name" => "Casa Merlò",
//         "description" => "Sinfonia di Sapori: Il nostro ristorante è un palcoscenico dove i gusti si fondono in un'armonia perfetta, creando una sinfonia di sapori indimenticabile.",
//         "city" => "Bologna",
//         "address" => "Via de' Gombruti, 2/D",
//         "vat" => "7843569021",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/ba8620c8-6e04-4177-97df-2beaba3921cf/e55c891b-f0f0-4b48-b2c4-281d8aec5401.jpg",
//         "priceRange" => 30,
//         "rating_value" => 5,
//         "review_count" => 63,
//     ],
//     [
//         "categories" => [1, 2, 4],
//         "name" => "Capriccio",
//         "description" => "Rivoluzione del Gusto: Entra nel futuro della cucina, dove la scienza e l'arte si fondono per creare piatti rivoluzionari che sfidano ogni aspettativa.",
//         "city" => "Bologna",
//         "address" => "Via Domodossola, 3",
//         "vat" => "3129456780",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/076e41db-8d29-4919-b2d5-718e4481401b/c095d7b5-c75a-4a1c-9fdc-841d00510670.jpg",
//         "priceRange" => 35,
//         "rating_value" => 6,
//         "review_count" => 114,
//     ],
//     [
//         "categories" => [1, 4],
//         "name" => "Terrazza Merliani 2.0",
//         "description" => "Ristorante Spezzato dal Tempo: Un luogo dove passato, presente e futuro si incontrano nel piatto, creando un'esperienza senza tempo che delizia i sensi.",
//         "city" => "Napoli",
//         "address" => "Via Giovanni Merliani, 73",
//         "vat" => "5672309184",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/2f0b66e2-22d3-455a-866c-ee8c218a1ba9/5a05b2f0-9ed9-4f8e-99dd-0dab1b4bdf41.jpg",
//         "priceRange" => 15,
//         "rating_value" => 9,
//         "review_count" => 415,
//     ],
//     [
//         "categories" => [4],
//         "name" => "Nam 43",
//         "description" => "Sapori Nascosti: Scopri il lato segreto della cucina, dove ingredienti insoliti si rivelano in piatti straordinari che stupiscono anche i palati più esperti.",
//         "city" => "Napoli",
//         "address" => "Via Santa Maria di Costantinopoli, 43",
//         "vat" => "1248703569",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/8feb2468-011a-4420-b171-b4d591d0d861/a40b0776-a837-41e4-b669-1c2bcc9b909a.jpg",
//         "priceRange" => 15,
//         "rating_value" => 7,
//         "review_count" => 431,
//     ],
//     [
//         "categories" => [1, 3, 4],
//         "name" => "Locanda dei Buoni e Cattivi",
//         "description" => "Caleidoscopio Culinario: Il nostro ristorante è un viaggio attraverso colori, forme e gusti in continua evoluzione, offrendo un'esperienza visiva e gustativa unica.",
//         "city" => "Cagliari",
//         "address" => "Via Vittorio Veneto, 96",
//         "vat" => "8950341627",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/9ccd0911-36ce-4053-9fdd-fd45cde7d078/84e8edf8-aae4-4b12-b436-f9f79c79b70d.jpg",
//         "priceRange" => 25,
//         "rating_value" => 4,
//         "review_count" => 480,
//     ],
//     [
//         "categories" => [1, 4],
//         "name" => "Obicà  Mozzarella Bar",
//         "description" => "Ristorante degli Inganni: Nulla è come sembra in questo mondo di illusioni gastronomiche, dove i piatti sfidano la percezione e stupiscono ogni ospite.",
//         "city" => "Cagliari",
//         "address" => "Via Roma, 143",
//         "vat" => "6701589324",
//         "url_image" => "https://res.cloudinary.com/tf-lab/image/upload/restaurant/3c4660f4-3f25-45fa-93ed-715a3544f968/d24efa9e-3952-450b-9f9a-b3487aca5b9b.jpg",
//         "priceRange" => 24,
//         "rating_value" => 9,
//         "review_count" => 101,
//     ],
];
