<?php

return [
    [
        "name"          => "Pollo al Curry Cremoso",
        "ingredients"   => "Pollo, cipolla, aglio, zenzero, curry in polvere, latte di cocco, panna, pomodori pelati, olio d'oliva, sale, pepe, coriandolo fresco",
        "price"         => 13,
        "description"   => "Un piatto ricco e avvolgente, il Pollo al Curry Cremoso unisce pezzi di pollo teneri e succulenti a una salsa di curry vellutata. Servito su un letto di riso aromatico, è un comfort food con un tocco esotico",
        "url_image"         => "https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2020/07/Petto-di-pollo-al-curry-0920_2.jpg",
        "restaurant_id" => 1,
        "visible"       => true,
    ],
    [
        "name"          => "Pollo Tikka Masala",
        "ingredients"   => "Pollo, yogurt, spezie tikka masala, pomodori, cipolla, aglio, zenzero, panna, coriandolo",
        "price"         => 10,
        "description"   => "Un'iconica pietanza indiana, il Pollo Tikka Masala offre pezzi di pollo teneri marinati e cotti in una salsa cremosa e speziata. Servito con riso basmati e coriandolo fresco.",
        "url_image"     => "https://www.giallozafferano.it/images/171-17176/Pollo-tikka-masala_450x300.jpg",
        "restaurant_id" => 1,
        "visible"       => true,
    ],
    [
        "name"          => "Pollo Teriyaki con Verdure",
        "ingredients"   => "Pollo, salsa teriyaki, carote, zucchine, peperoni, cipolla, aglio, zenzero, olio di sesamo, riso, cipollotti",
        "price"         => 15,
        "description"   => "Una pietanza asiatica appagante, il Pollo Teriyaki con Verdure combina pezzi di pollo marinati con una salsa teriyaki dolce e salata, serviti con verdure croccanti",
        "url_image"         => "https://blog.giallozafferano.it/delizieinpentola/wp-content/uploads/2021/10/Pollo-in-salsa-teriyaki.jpg",
        "restaurant_id" => 1,
        "visible"       => true,
    ],
    [
        "name"          => "Sushi Rolls Vegetariani",
        "ingredients"   => "Fogli di nori, riso per sushi, avocado, carota, cetriolo, peperone, aceto di riso, zucchero, sale",
        "price"         => 12,
        "description"   => "I Sushi Rolls Vegetariani sono un'opzione fresca e colorata. Avocado, carota, cetriolo e peperone si arrotolano in nori e riso, per creare un pasto leggero e gustoso",
        "url_image"         => "https://www.giallozafferano.it/images/155-15516/Sushi-vegetariano_780x520_wm.jpg",
        "restaurant_id" => 1,
        "visible"       => true,
    ],
    // RISTORANTE 2
    [
        "name"          => "Pizza Margherita",
        "ingredients"   => "Pasta per pizza, mozzarella, pomodori maturi, basilico fresco, olio d'oliva, sale",
        "price"         => 6,
        "description"   => "La Pizza Margherita è una creazione classica che celebra i sapori semplici dell'Italia. Base di pizza, mozzarella, pomodori e basilico si combinano per un'esplosione di sapore",
        "url_image"         => "https://www.giallozafferano.it/images/249-24919/Pizza-napoletana_450x300.jpg",
        "restaurant_id" => 2,
        "visible"       => true,
    ],
    [
        "name"          => "Insalata Caprese",
        "ingredients"   => "Mozzarella di bufala, pomodori maturi, basilico fresco, olio d'oliva extravergine, aceto balsamico, sale, pepe",
        "price"         => 8,
        "description"   => "L'Insalata Caprese è un classico italiano che celebra i sapori semplici e freschi. Mozzarella di bufala, pomodori e basilico si fondono con olio d'oliva extravergine per una combinazione irresistibile",
        "url_image"         => "https://media-assets.lacucinaitaliana.it/photos/64b938d160df211dd0c14782/16:9/w_1920,c_limit/shutterstock_508377580.jpg",
        "restaurant_id" => 2,
        "visible"       => true,
    ],
    [
        "name"          => "Zuppa di Lenticchie Rosse",
        "ingredients"   => "Lenticchie rosse, carote, sedano, cipolla, aglio, pomodori a cubetti, brodo vegetale, cumino, curcuma, paprika, olio d'oliva, sale, pepe",
        "price"         => 10,
        "description"   => "Nutriente e confortante, la Zuppa di Lenticchie Rosse è ricca di proteine e fibre. Le lenticchie si uniscono a verdure e spezie per creare una zuppa dal sapore avvolgente",
        "url_image"         => "https://blog.giallozafferano.it/ortaggichepassionebysara/wp-content/uploads/2021/04/P1600925-zuppa-di-lenticchie-rosse-decorticate-1000x750.jpg",
        "restaurant_id" => 2,
        "visible"       => true,
    ],
    [
        "name"          => "Omelette Primaverile",
        "ingredients"   => "Uova, asparagi, piselli, formaggio feta, cipolla verde, prezzemolo, burro, sale, pepe",
        "price"         => 7,
        "description"   => "L'Omelette Primaverile è una colazione sana e colorata. Uova leggere si combinano con asparagi croccanti, piselli dolci e formaggio feta per iniziare la giornata con energia",
        "url_image"         => "https://blog.giallozafferano.it/passionecooking/wp-content/uploads/2019/06/Omlett-con-pomodori-e-cipollotti-ripiena-di-formaggio_006.jpg",
        "restaurant_id" => 2,
        "visible"       => true,
    ],
    // RISTORANTE 3
    [
        "name"          => "Pasta al pesto di Zucchine e Mandorle",
        "ingredients"   => "Pasta, zucchine, mandorle, pecorino grattugiato, aglio, olio d'oliva, succo di limone, sale, pepe",
        "price"         => 10,
        "description"   => "Un'alternativa leggera al classico pesto, il Pesto di Zucchine e Mandorle combina zucchine grigliate, mandorle tostate e pecorino per una salsa fresca e cremosa",
        "url_image"         => "https://blog.giallozafferano.it/valeriaciccotti/wp-content/uploads/2019/04/farfalle-blog.jpg",
        "restaurant_id" => 3,
        "visible"       => true,
    ],
    [
        "name"          => "Insalata di Riso Mediterranea",
        "ingredients"   => "Riso integrale, pomodori, cetrioli, olive nere, feta, cipolla rossa, prezzemolo, olio d'oliva, succo di limone, sale, pepe",
        "price"         => 10,
        "description"   => "Un'insalata completa e saporita, l'Insalata di Riso Mediterranea unisce riso integrale con pomodori, cetrioli, olive e feta, il tutto condito con un dressing all'olio d'oliva",
        "url_image"         => "https://blog.giallozafferano.it/ladietamediterranea/wp-content/uploads/2015/08/insalata-di-riso-ciotola-dieta-mediterranea.jpg",
        "restaurant_id" => 3,
        "visible"       => true,
    ],
    [
        "name"          => "Pasta al Pomodoro Fresco",
        "ingredients"   => "Pasta, pomodori maturi, aglio, basilico fresco, olio d'oliva, sale, pepe",
        "price"         => 10,
        "description"   => "La Pasta al Pomodoro Fresco è una celebrazione della semplicità. Pomodori maturi, aglio e basilico si combinano per creare una salsa ricca e saporita per la pasta",
        "url_image"         => "https://blog.giallozafferano.it/studentiaifornelli/wp-content/uploads/2020/06/2020-spaghetti-al-pomodoro-fresco-ricetta-pasta-al-sugo-di-pomodoro-fresco.jpg",
        "restaurant_id" => 3,
        "visible"       => true,
    ],
    [
        "name"          => "Risotto ai Funghi Porcini",
        "ingredients"   => "Riso Arborio, funghi porcini secchi, brodo vegetale, cipolla, vino bianco, burro, parmigiano grattugiato, prezzemolo, sale, pepe",
        "price"         => 18,
        "description"   => "Un comfort food di lusso, il Risotto ai Funghi Porcini unisce il ricco sapore dei funghi porcini con la cremosità del risotto. Un piatto caldo e avvolgente per le serate fresche",
        "url_image"         => "https://oliofarchioni.com/wp-content/uploads/2021/09/risotto-ai-funghi-porcini-1.jpg",
        "restaurant_id" => 3,
        "visible"       => true,
    ],
    // RISTORANTE 4
    [
        "name"          => "Melanzane Parmigiana",
        "ingredients"   => "Melanzane, salsa di pomodoro, mozzarella, parmigiano grattugiato, basilico fresco, uova, pangrattato, olio d'oliva, sale, pepe",
        "price"         => 12,
        "description"   => "Una creazione italiana deliziosa e sostanziosa, la Melanzane Parmigiana combina fette di melanzane impanate, salsa di pomodoro e formaggi fondenti",
        "url_image"         => "https://www.giallozafferano.it/images/234-23446/Parmigiana-di-melanzane_450x300.jpg",
        "restaurant_id" => 4,
        "visible"       => true,
    ],
    [
        "name"          => "Quiche agli Spinaci e Formaggio di Capra",
        "ingredients"   => "Pasta per crosta di quiche, spinaci freschi, formaggio di capra, uova, panna, cipolla, noce moscata, sale, pepe",
        "price"         => 12,
        "description"   => "Una quiche elegante e saporita, la Quiche agli Spinaci e Formaggio di Capra unisce spinaci freschi e formaggio di capra cremoso in una crosta croccante. Perfetta per pranzi o cene speciali",
        "url_image"         => "https://blog.giallozafferano.it/kissthecook/wp-content/uploads/2016/05/Torta-salata-con-spinaci-e-caprino.-768x576.jpg",
        "restaurant_id" => 4,
        "visible"       => true,
    ],
    [
        "name"          => "Insalata di Couscous Mediterranea",
        "ingredients"   => "Couscous, pomodori, cetrioli, peperoni, olive nere, cipolla rossa, prezzemolo, limone, olio d'oliva, sale, pepe",
        "price"         => 8,
        "description"   => "Un'insalata leggera e nutriente, l'Insalata di Couscous Mediterranea unisce couscous, verdure croccanti e olive nere, condite con un dressing al limone e olio d'oliva",
        "url_image"         => "https://blog.giallozafferano.it/lericettedimatilde/wp-content/uploads/2020/07/1B8A19FD-E2E9-4D73-91D9-C6BF7F8C6BF3-768x1024.jpeg",
        "restaurant_id" => 4,
        "visible"       => true,
    ],
    [
        "name"          => "Insalata di Quinoa Mediterranea",
        "ingredients"   => "Quinoa, pomodori, cetrioli, olive, feta, cipolla rossa, prezzemolo, succo di limone, olio d'oliva, sale, pepe",
        "price"         => 10,
        "description"   => "Un'insalata fresca e nutriente che fonde la quinoa con sapori mediterranei. Pomodori dolci, cetrioli croccanti, olive salate e feta cremosa si uniscono per creare un'esplosione di gusto",
        "url_image"         => "https://www.liberaincucina.it/wp-content/uploads/2023/06/insalata-di-quinoa-alla-mediterranea-800x600.jpg",
        "restaurant_id" => 4,
        "visible"       => true,
    ],
    // RISTORANTE 5
    [
        "name"          => "Crostata alle Fragole",
        "ingredients"   => "Pasta frolla, fragole, zucchero, gelatina di fragole, succo di limone",
        "price"         => 6,
        "description"   => "Un dessert fresco e dolce, la Crostata alle Fragole combina una crosta friabile con fragole mature e una glassa lucida per un'esplosione di sapori fruttati",
        "url_image"         => "https://www.giallozafferano.it/images/210-21097/Crostata-di-fragole-fresche_450x300.jpg",
        "restaurant_id" => 5,
        "visible"       => true,
    ],
    [
        "name"          => "Crepes Ripiene di Ricotta e Spinaci",
        "ingredients"   => "Crepes, ricotta, spinaci, uova, latte, farina, noce moscata, burro, formaggio grattugiato",
        "price"         => 7,
        "description"   => "Un piatto versatile, le Crepes Ripiene di Ricotta e Spinaci combinano crepes sottili con una miscela di ricotta e spinaci, il tutto condito con salsa bianca e formaggio",
        "url_image"         => "https://www.giallozafferano.it/images/166-16674/Crepes-ricotta-e-spinaci_780x520_wm.jpg",
        "restaurant_id" => 5,
        "visible"       => true,
    ],
    [
        "name"          => "Penne al Salmone e Asparagi",
        "ingredients"   => "Penne, salmone affumicato, asparagi, panna, succo di limone, cipolla, vino bianco, olio d'oliva, sale, pepe",
        "price"         => 13,
        "description"   => "Un piatto elegante e saporito, le Penne al Salmone e Asparagi combinano pasta penne con salmone affumicato, asparagi croccanti e una salsa leggera al limone",
        "url_image"         => "https://blog.giallozafferano.it/cucinoperpassione/wp-content/uploads/2018/06/Pasta-salmone-e-asparagi.jpg",
        "restaurant_id" => 5,
        "visible"       => true,
    ],
    [
        "name"          => "Frittata al Prosciutto e Formaggio",
        "ingredients"   => "Uova, prosciutto cotto, formaggio Cheddar, cipolla, prezzemolo, burro, sale, pepe",
        "price"         => 12,
        "description"   => "Una frittata abbondante e saporita, la Frittata al Prosciutto e Formaggio unisce uova, prosciutto cotto e formaggio Cheddar per una colazione o un pranzo sostanzioso",
        "url_image"         => "https://blog.giallozafferano.it/letortedigessica/wp-content/uploads/2017/03/rotolo-di-frittata.jpg",
        "restaurant_id" => 5,
        "visible"       => true,
    ],
    // RISTORANTE 6
    [
        "name"          => "Gnocchi alla Sorrentina",
        "ingredients"   => "Gnocchi, pomodori a cubetti, mozzarella, basilico fresco, olio d'oliva, aglio, sale, pepe",
        "price"         => 12,
        "description"   => "Gnocchi alla Sorrentina",
        "url_image"         => "https://www.giallozafferano.it/images/197-19745/Gnocchi-alla-sorrentina_450x300.jpg",
        "restaurant_id" => 6,
        "visible"       => true,
    ],
    [
        "name"          => "Tagliatelle al Salmone Affumicato",
        "ingredients"   => "Tagliatelle, salmone affumicato, panna, succo di limone, cipolla, vino bianco, olio d'oliva, sale, pepe, aneto fresco",
        "price"         => 16,
        "description"   => "Un piatto elegante e delizioso, le Tagliatelle al Salmone Affumicato sono una fusione di pasta fresca e salmone delicato. Una salsa leggera al limone completa questa prelibatezza",
        "url_image"         => "https://i2.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2018/05/3582_Tagliatelle.jpg?resize=895%2C616&ssl=1",
        "restaurant_id" => 6,
        "visible"       => true,
    ],
    [
        "name"          => "Salmone alla Griglia con Salsa di Mango",
        "ingredients"   => "Salmone, mango, peperoncino, cipolla rossa, coriandolo, lime, olio d'oliva, sale, pepe",
        "price"         => 16,
        "description"   => "Il Salmone alla Griglia con Salsa di Mango è una combinazione di sapori freschi e contrastanti. Il salmone grigliato è arricchito da una salsa di mango dolce e piccante",
        "url_image"         => "https://ricette.lidl.ch/var/site/storage/images/_aliases/1440x495/4/0/1/3/153104-2-ita-CH/Filetto-di-salmone-in-crosta-di-sesamo-su-salsa-di-mango.jpg",
        "restaurant_id" => 6,
        "visible"       => true,
    ],
    [
        "name"          => "Gamberi Aglio e Limone",
        "ingredients"   => "Gamberi, aglio, limone, prezzemolo, olio d'oliva, sale, pepe",
        "price"         => 18,
        "description"   => "I Gamberi Aglio e Limone sono una deliziosa prelibatezza marina. Gamberi succosi vengono cotti con aglio fragrante e succo di limone per un piatto fresco e leggero",
        "url_image"         => "https://blog.giallozafferano.it/allacciateilgrembiule/wp-content/uploads/2019/07/gamberi-al-limone.jpg",
        "restaurant_id" => 6,
        "visible"       => true,
    ],
    // RISTORANTE 7
    [
        "name"          => "Pollo al Rosmarino con Patate",
        "ingredients"   => "Pollo, patate, rosmarino, aglio, limone, olio d'oliva, sale, pepe",
        "price"         => 15,
        "description"   => "Un piatto rustico e aromatico, il Pollo al Rosmarino con Patate unisce pezzi di pollo succulenti con patate arrosto profumate al rosmarino. Un comfort food dal sapore intenso",
        "url_image"         => "https://blog.giallozafferano.it/melacannellaefantasia/wp-content/uploads/2019/02/fusi-di-pollo-al-forno-con-patate.jpg",
        "restaurant_id" => 7,
        "visible"       => true,
    ],
    [
        "name"          => "Spaghetti alla Carbonara",
        "ingredients"   => "Spaghetti, pancetta, uova, formaggio pecorino, pepe nero, olio d'oliva, sale",
        "price"         => 12,
        "description"   => "Un classico italiano, gli Spaghetti alla Carbonara combinano uova, pancetta croccante e formaggio pecorino. Una pasta cremosa e saporita che conquista ogni palato",
        "url_image"         => "https://blog.giallozafferano.it/paola67/wp-content/uploads/2020/04/Spaghetti-alla-carbonara.jpg",
        "restaurant_id" => 7,
        "visible"       => true,
    ],
    [
        "name"          => "Lasagna al Forno con Besciamella",
        "ingredients"   => "Pasta per lasagna, carne macinata, pomodoro, cipolla, aglio, mozzarella, besciamella, parmigiano reggiano, basilico",
        "price"         => 12,
        "description"   => "Una classica comfort food, la Lasagna al Forno con Besciamella combina strati di pasta, carne saporita, mozzarella filante e una deliziosa besciamella. Un'esplosione di sapori e consistenze.",
        "url_image"     => "https://www.giallozafferano.it/images/229-22941/Lasagne-alla-Bolognese_360x300.jpg",
        "restaurant_id" => 7,
        "visible"       => true,
    ],
    [
        "name"          => "Sformato di Spinaci",
        "ingredients"   => "Spinaci freschi, uova, panna, formaggio Parmigiano, burro, noce moscata, sale, pepe",
        "price"         => 10,
        "description"   => "Un piatto elegante e saporito, lo Sformato di Spinaci unisce spinaci freschi con uova, panna e formaggio Parmigiano, il tutto cotto al forno per una consistenza soffice",
        "url_image"         => "https://www.giallozafferano.it/images/31-3167/Flan-di-spinaci-e-taleggio_780x520_wm.jpg",
        "restaurant_id" => 7,
        "visible"       => true,
    ],
    // RISTORANTE 8
    [
        "name"          => "Wraps di Pollo Caesar",
        "ingredients"   => "Tortillas, pollo grigliato, lattuga romana, parmigiano grattugiato, salsa Caesar, crouton, pepe nero",
        "price"         => 10,
        "description"   => "I Wraps di Pollo Caesar portano il classico sapore dell'insalata Caesar in un involucro. Pollo grigliato, lattuga croccante e salsa Caesar si fondono in un pasto leggero ma soddisfacente",
        "url_image"         => "https://blog.giallozafferano.it/coloriesaporiincucina/wp-content/uploads/2022/04/wrap-con-pollo-e-salsa-caesar.jpg",
        "restaurant_id" => 8,
        "visible"       => true,
    ],
    [
        "name"          => "Tacos al Pastor",
        "ingredients"   => "Carne di maiale marinata, ananas, cipolla, coriandolo, lime, tortillas di mais",
        "price"         => 9,
        "description"   => "I Tacos al Pastor sono una prelibatezza messicana. Carne di maiale marinata viene cucinata allo spiedo, servita in tortillas di mais e guarnita con ananas, cipolla, coriandolo e una spruzzata di lime.",
        "url_image"     => "https://blog.giallozafferano.it/lastefyincucina/wp-content/uploads/2021/02/IMG-3400-960x960.jpg",
        "restaurant_id" => 8,
        "visible"       => true,
    ],
    [
        "name"          => "Tacos di Pollo alla Griglia",
        "ingredients"   => "Pollo, tortillas di mais, lime, coriandolo, cipolla rossa, peperoncino jalapeño, salsa di pomodoro, avocado, formaggio Cheddar, panna acida",
        "price"         => 8,
        "description"   => "I Tacos di Pollo alla Griglia portano il sapore dell'estate nel tuo piatto. Il pollo marinato e grigliato è avvolto in tortillas calde e accompagnato da una selezione di salse e condimenti",
        "url_image"         => "https://blog.giallozafferano.it/ricciaifornelli/wp-content/uploads/2017/03/Tacos-di-pollo.jpg",
        "restaurant_id" => 8,
        "visible"       => true,
    ],
    [
        "name"          => "Mousse al Cioccolato",
        "ingredients"   => "Cioccolato fondente, panna, uova, zucchero, vaniglia",
        "price"         => 6,
        "description"   => "Un dessert indulgente e vellutato, la Mousse al Cioccolato unisce cioccolato fondente fuso con panna montata, creando una mousse leggera e irresistibile",
        "url_image"         => "https://www.giallozafferano.it/images/216-21643/Mousse-al-cioccolato_450x300.jpg",
        "restaurant_id" => 8,
        "visible"       => true,
    ],
];
