<?php

return [
    [
        "name"          => "Pollo al Curry Cremoso",
        "description"   => "Un piatto ricco e avvolgente, il Pollo al Curry Cremoso unisce pezzi di pollo teneri e succulenti a una salsa di curry vellutata. Servito su un letto di riso aromatico, è un comfort food con un tocco esotico",
        "price"         => 13,
        "ingredients"   => "Pollo, cipolla, aglio, zenzero, curry in polvere, latte di cocco, panna, pomodori pelati, olio d'oliva, sale, pepe, coriandolo fresco",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Insalata di Quinoa Mediterranea",
        "description"   => "Un'insalata fresca e nutriente che fonde la quinoa con sapori mediterranei. Pomodori dolci, cetrioli croccanti, olive salate e feta cremosa si uniscono per creare un'esplosione di gusto",
        "price"         => 10,
        "ingredients"   => "Quinoa, pomodori, cetrioli, olive, feta, cipolla rossa, prezzemolo, succo di limone, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Tagliatelle al Salmone Affumicato",
        "description"   => "Un piatto elegante e delizioso, le Tagliatelle al Salmone Affumicato sono una fusione di pasta fresca e salmone delicato. Una salsa leggera al limone completa questa prelibatezza",
        "price"         => 16,
        "ingredients"   => "Tagliatelle, salmone affumicato, panna, succo di limone, cipolla, vino bianco, olio d'oliva, sale, pepe, aneto fresco",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Risotto ai Funghi Porcini",
        "description"   => "Un comfort food di lusso, il Risotto ai Funghi Porcini unisce il ricco sapore dei funghi porcini con la cremosità del risotto. Un piatto caldo e avvolgente per le serate fresche",
        "price"         => 18,
        "ingredients"   => "Riso Arborio, funghi porcini secchi, brodo vegetale, cipolla, vino bianco, burro, parmigiano grattugiato, prezzemolo, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Tacos di Pollo alla Griglia",
        "description"   => "I Tacos di Pollo alla Griglia portano il sapore dell'estate nel tuo piatto. Il pollo marinato e grigliato è avvolto in tortillas calde e accompagnato da una selezione di salse e condimenti",
        "price"         => 8,
        "ingredients"   => "Pollo, tortillas di mais, lime, coriandolo, cipolla rossa, peperoncino jalapeño, salsa di pomodoro, avocado, formaggio Cheddar, panna acida",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Insalata Caprese",
        "description"   => "L'Insalata Caprese è un classico italiano che celebra i sapori semplici e freschi. Mozzarella di bufala, pomodori e basilico si fondono con olio d'oliva extravergine per una combinazione irresistibile",
        "price"         => 8,
        "ingredients"   => "Mozzarella di bufala, pomodori maturi, basilico fresco, olio d'oliva extravergine, aceto balsamico, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Zuppa di Lenticchie Rosse",
        "description"   => "Nutriente e confortante, la Zuppa di Lenticchie Rosse è ricca di proteine e fibre. Le lenticchie si uniscono a verdure e spezie per creare una zuppa dal sapore avvolgente",
        "price"         => 10,
        "ingredients"   => "Lenticchie rosse, carote, sedano, cipolla, aglio, pomodori a cubetti, brodo vegetale, cumino, curcuma, paprika, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Omelette Primaverile",
        "description"   => "L'Omelette Primaverile è una colazione sana e colorata. Uova leggere si combinano con asparagi croccanti, piselli dolci e formaggio feta per iniziare la giornata con energia",
        "price"         => 7,
        "ingredients"   => "Uova, asparagi, piselli, formaggio feta, cipolla verde, prezzemolo, burro, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Spaghetti alla Carbonara",
        "description"   => "Un classico italiano, gli Spaghetti alla Carbonara combinano uova, pancetta croccante e formaggio pecorino. Una pasta cremosa e saporita che conquista ogni palato",
        "price"         => 12,
        "ingredients"   => "Spaghetti, pancetta, uova, formaggio pecorino, pepe nero, olio d'oliva, sale",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Gamberi Aglio e Limone",
        "description"   => "I Gamberi Aglio e Limone sono una deliziosa prelibatezza marina. Gamberi succosi vengono cotti con aglio fragrante e succo di limone per un piatto fresco e leggero",
        "price"         => 18,
        "ingredients"   => "Gamberi, aglio, limone, prezzemolo, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Insalata di Riso Mediterranea",
        "description"   => "Un'insalata completa e saporita, l'Insalata di Riso Mediterranea unisce riso integrale con pomodori, cetrioli, olive e feta, il tutto condito con un dressing all'olio d'oliva",
        "price"         => 10,
        "ingredients"   => "Riso integrale, pomodori, cetrioli, olive nere, feta, cipolla rossa, prezzemolo, olio d'oliva, succo di limone, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Pollo al Rosmarino con Patate",
        "description"   => "Un piatto rustico e aromatico, il Pollo al Rosmarino con Patate unisce pezzi di pollo succulenti con patate arrosto profumate al rosmarino. Un comfort food dal sapore intenso",
        "price"         => 15,
        "ingredients"   => "Pollo, patate, rosmarino, aglio, limone, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Salmone alla Griglia con Salsa di Mango",
        "description"   => "Il Salmone alla Griglia con Salsa di Mango è una combinazione di sapori freschi e contrastanti. Il salmone grigliato è arricchito da una salsa di mango dolce e piccante",
        "price"         => 16,
        "ingredients"   => "Salmone, mango, peperoncino, cipolla rossa, coriandolo, lime, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Pizza Margherita",
        "description"   => "La Pizza Margherita è una creazione classica che celebra i sapori semplici dell'Italia. Base di pizza, mozzarella, pomodori e basilico si combinano per un'esplosione di sapore",
        "price"         => 6,
        "ingredients"   => "Pasta per pizza, mozzarella, pomodori maturi, basilico fresco, olio d'oliva, sale",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Quiche agli Spinaci e Formaggio di Capra",
        "description"   => "Una quiche elegante e saporita, la Quiche agli Spinaci e Formaggio di Capra unisce spinaci freschi e formaggio di capra cremoso in una crosta croccante. Perfetta per pranzi o cene speciali",
        "price"         => 12,
        "ingredients"   => "Pasta per crosta di quiche, spinaci freschi, formaggio di capra, uova, panna, cipolla, noce moscata, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Pasta al Pomodoro Fresco",
        "description"   => "La Pasta al Pomodoro Fresco è una celebrazione della semplicità. Pomodori maturi, aglio e basilico si combinano per creare una salsa ricca e saporita per la pasta",
        "price"         => 10,
        "ingredients"   => "Pasta, pomodori maturi, aglio, basilico fresco, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Crostata alle Fragole",
        "description"   => "Un dessert fresco e dolce, la Crostata alle Fragole combina una crosta friabile con fragole mature e una glassa lucida per un'esplosione di sapori fruttati",
        "price"         => 6,
        "ingredients"   => "Pasta frolla, fragole, zucchero, gelatina di fragole, succo di limone",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Pasta al pesto di Zucchine e Mandorle",
        "description"   => "Un'alternativa leggera al classico pesto, il Pesto di Zucchine e Mandorle combina zucchine grigliate, mandorle tostate e pecorino per una salsa fresca e cremosa",
        "price"         => 10,
        "ingredients"   => "Pasta, zucchine, mandorle, pecorino grattugiato, aglio, olio d'oliva, succo di limone, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Penne al Salmone e Asparagi",
        "description"   => "Un piatto elegante e saporito, le Penne al Salmone e Asparagi combinano pasta penne con salmone affumicato, asparagi croccanti e una salsa leggera al limone",
        "price"         => 13,
        "ingredients"   => "Penne, salmone affumicato, asparagi, panna, succo di limone, cipolla, vino bianco, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Frittata al Prosciutto e Formaggio",
        "description"   => "Una frittata abbondante e saporita, la Frittata al Prosciutto e Formaggio unisce uova, prosciutto cotto e formaggio Cheddar per una colazione o un pranzo sostanzioso",
        "price"         => 12,
        "ingredients"   => "Uova, prosciutto cotto, formaggio Cheddar, cipolla, prezzemolo, burro, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Gnocchi alla Sorrentina",
        "description"   => "Gnocchi alla Sorrentina",
        "price"         => 12,
        "ingredients"   => "Gnocchi, pomodori a cubetti, mozzarella, basilico fresco, olio d'oliva, aglio, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Pollo Teriyaki con Verdure",
        "description"   => "Una pietanza asiatica appagante, il Pollo Teriyaki con Verdure combina pezzi di pollo marinati con una salsa teriyaki dolce e salata, serviti con verdure croccanti",
        "price"         => 15,
        "ingredients"   => "Pollo, salsa teriyaki, carote, zucchine, peperoni, cipolla, aglio, zenzero, olio di sesamo, riso, cipollotti",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Melanzane Parmigiana",
        "description"   => "Una creazione italiana deliziosa e sostanziosa, la Melanzane Parmigiana combina fette di melanzane impanate, salsa di pomodoro e formaggi fondenti",
        "price"         => 12,
        "ingredients"   => "Melanzane, salsa di pomodoro, mozzarella, parmigiano grattugiato, basilico fresco, uova, pangrattato, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Sformato di Spinaci",
        "description"   => "Un piatto elegante e saporito, lo Sformato di Spinaci unisce spinaci freschi con uova, panna e formaggio Parmigiano, il tutto cotto al forno per una consistenza soffice",
        "price"         => 10,
        "ingredients"   => "Spinaci freschi, uova, panna, formaggio Parmigiano, burro, noce moscata, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Wraps di Pollo Caesar",
        "description"   => "I Wraps di Pollo Caesar portano il classico sapore dell'insalata Caesar in un involucro. Pollo grigliato, lattuga croccante e salsa Caesar si fondono in un pasto leggero ma soddisfacente",
        "price"         => 10,
        "ingredients"   => "Tortillas, pollo grigliato, lattuga romana, parmigiano grattugiato, salsa Caesar, crouton, pepe nero",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Insalata di Couscous Mediterranea",
        "description"   => "Un'insalata leggera e nutriente, l'Insalata di Couscous Mediterranea unisce couscous, verdure croccanti e olive nere, condite con un dressing al limone e olio d'oliva",
        "price"         => 8,
        "ingredients"   => "Couscous, pomodori, cetrioli, peperoni, olive nere, cipolla rossa, prezzemolo, limone, olio d'oliva, sale, pepe",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Sushi Rolls Vegetariani",
        "description"   => "I Sushi Rolls Vegetariani sono un'opzione fresca e colorata. Avocado, carota, cetriolo e peperone si arrotolano in nori e riso, per creare un pasto leggero e gustoso",
        "price"         => 12,
        "ingredients"   => "Fogli di nori, riso per sushi, avocado, carota, cetriolo, peperone, aceto di riso, zucchero, sale",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Mousse al Cioccolato",
        "description"   => "Un dessert indulgente e vellutato, la Mousse al Cioccolato unisce cioccolato fondente fuso con panna montata, creando una mousse leggera e irresistibile",
        "price"         => 6,
        "ingredients"   => "Cioccolato fondente, panna, uova, zucchero, vaniglia",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
    [
        "name"          => "Crepes Ripiene di Ricotta e Spinaci",
        "description"   => "Un piatto versatile, le Crepes Ripiene di Ricotta e Spinaci combinano crepes sottili con una miscela di ricotta e spinaci, il tutto condito con salsa bianca e formaggio",
        "price"         => 7,
        "ingredients"   => "Crepes, ricotta, spinaci, uova, latte, farina, noce moscata, burro, formaggio grattugiato",
        "image"         => "https://cdn.cook.stbm.it/thumbnails/ricette/144/144286/hd750x421.jpg",
    ],
];